import { Poppins } from "next/font/google";

import "@/sass/globals.scss";
import { join } from "@/utils/helper";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={join(poppins.className)}>{children}</body>
    </html>
  );
}
